apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: order_service
  description: handles customer orders
  annotations:
    github.com/project-slug: curtissearle/Caffeine_Coders_Co
  tags:
    - python
  links:
    - url: https://www.helloworld.org/
      title: Production
      icon: dashboard
      type: dashboard
    - url: https://www.helloworld.org/
      title: Development
      icon: dashboard
      type: dashboard
spec:
  type: openapi
  lifecycle: production
  owner: group:default/API_Squad
  providesApi:
    - order_service
  definition:
    $text: ./swagger.json
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: authentication_service
  description: A auth service
  annotations:
    github.com/project-slug: curtissearle/Caffeine_Coders_Co
  tags:
    - python
  links:
    - url: https://www.helloworld.org/
      title: Production
      icon: dashboard
      type: dashboard
    - url: https://www.helloworld.org/
      title: Development
      icon: dashboard
      type: dashboard
spec:
  type: openapi
  lifecycle: production
  owner: group:default/API_Squad
  providesApi:
    - authentication_service
  definition:
    $text: ./swagger.json
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: logging_service
  description: A log service
  annotations:
    github.com/project-slug: curtissearle/Caffeine_Coders_Co
  tags:
    - javascript
  links:
    - url: https://www.helloworld.org/
      title: Production
      icon: dashboard
      type: dashboard
    - url: https://www.helloworld.org/
      title: Development
      icon: dashboard
      type: dashboard
spec:
  type: openapi
  lifecycle: production
  owner: group:default/API_Squad
  providesApi:
    - logging_service
  definition:
    $text: ./swagger.json
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payment_service
  description: A payment service
  annotations:
    github.com/project-slug: curtissearle/Caffeine_Coders_Co
  tags:
    - python
  links:
    - url: https://www.helloworld.org/
      title: Production
      icon: dashboard
      type: dashboard
    - url: https://www.helloworld.org/
      title: Development
      icon: dashboard
      type: dashboard
spec:
  type: openapi
  lifecycle: production
  owner: group:default/API_Squad
  providesApi:
    - payment_service
  definition:
    $text: ./swagger.json
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Support
  description: A hosted support portal
  annotations:
    github.com/project-slug: curtissearle/Caffeine_Coders_Co
  tags:
    - dashboard
  links:
    - url: https://www.helloworld.org/
      title: Production
      icon: dashboard
      type: dashboard
    - url: https://www.helloworld.org/
      title: Development
      icon: dashboard
      type: dashboard
spec:
  type: website
  lifecycle: production
  owner: group:default/Frontend_Squad
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Espresso_UI
  description: A frontend utilising an API
  annotations:
    github.com/project-slug: curtissearle/Caffeine_Coders_Co
    backstage.io/techdocs-ref: dir:.
  tags:
    - javascript
  links:
    - url: https://www.helloworld.org/
      title: Production
      icon: dashboard
      type: dashboard
spec:
  type: website
  lifecycle: production
  owner: group:default/Frontend_Squad
  dependsOn:
    - api:order_service
    - api:authentication_service
    - api:logging_service
    - api:payment_service
    - component:Support

    

